@REM DO NOT edit this file unless you're adding a new permanent script variable
@REM 1 - create a file called config.bat in this same directory
@REM 2 - Replace the variables with the paths for your machine

set project_root="C:\dev\src\github.com\gabrieldechichi\handmade-hero"
set vcvarsall_path="C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\Build\vcvarsall.bat"